daemon off;
pid /run/nginx.pid;
error_log stderr;
worker_processes 2;
events {
    worker_connections 1024;
}
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    types_hash_max_size 2048;
    index index.html index.htm;

    server {
        listen 5000;
        gzip on;
        gzip_min_length  1100;
        gzip_buffers  4 32k;
        gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
        gzip_vary on;
        gzip_comp_level  6;
        error_page   404  /404.html;

        location / {
            root "/app/dewasted.net/dist";
        }

        location /retro/ {
            alias "/app/retro-demos/dist";
        }

        location /asteroids/ {
            alias "/app/asteroidz";
        }

        location = /404.html {
            root "/app/dewasted.net/dist";
        }
    }
}